### ISSUE TITLE
Combat - Unknown - Unable to kill enemy ship

### ISSUE THREAD

**Issue by collinnolen** [jgayewu/pirategame#35]
During Combat I was unable to destroy the enemy ship with the 'I win' button. Couldn't win by defeating them the legit way either.

**Comment by collinnolen** [comment]
I will look into this when I get a chance to find out which file I think the issue is coming from, it might be a nav related thing.

**Comment by jgayewu** [comment]
Issue is in CombatManager.cs, "WriteData" function. 

StaticEnemies.GetCurrentEnemy().SetHitPoints(playerData.currentShipHP, playerData.currentCrewHP);

should be

StaticEnemies.GetCurrentEnemy().SetHitPoints(enemyData.currentShipHP, enemyData.currentCrewHP);
